import { EthicsReviewResult } from '@/types/ethics';
import { DetectedCapability, MisuseScenario } from '@/data/mockMisuseData';

interface ExportData {
  result: EthicsReviewResult;
  capabilities: DetectedCapability[];
  misuseScenarios: MisuseScenario[];
}

const severityEmoji: Record<string, string> = {
  safe: '✅',
  low: '🟢',
  medium: '🟡',
  high: '🟠',
  critical: '🔴',
};

export function exportAsMarkdown({ result, capabilities, misuseScenarios }: ExportData): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Ethical Review Report: ${result.projectName}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date(result.timestamp).toLocaleString()}`);
  lines.push(`**Overall Status:** ${severityEmoji[result.overallStatus]} ${result.overallStatus.toUpperCase()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total Issues:** ${result.issues.length}`);
  lines.push(`- **Detected Capabilities:** ${capabilities.length}`);
  lines.push(`- **Misuse Scenarios:** ${misuseScenarios.length}`);
  const criticalCount = misuseScenarios.filter(s => s.severity === 'critical').length;
  if (criticalCount > 0) {
    lines.push(`- **Critical Risks:** ${criticalCount}`);
  }
  lines.push('');

  // Detected Capabilities
  if (capabilities.length > 0) {
    lines.push('## Detected Capabilities');
    lines.push('');
    for (const cap of capabilities) {
      const riskLabel = cap.riskLevel === 'high' ? '⚠️ High Risk' : cap.riskLevel === 'medium' ? '⚡ Medium Risk' : '✓ Low Risk';
      lines.push(`### ${cap.name}`);
      lines.push('');
      lines.push(`**Risk Level:** ${riskLabel}`);
      lines.push('');
      lines.push(cap.description);
      lines.push('');
      if (cap.detectedIn.length > 0) {
        lines.push('**Detected in:**');
        for (const file of cap.detectedIn) {
          lines.push(`- \`${file}\``);
        }
        lines.push('');
      }
    }
  }

  // Misuse Scenarios
  if (misuseScenarios.length > 0) {
    lines.push('## Potential Misuse Scenarios');
    lines.push('');
    
    const sorted = [...misuseScenarios].sort((a, b) => {
      const order = { critical: 0, high: 1, medium: 2 };
      return order[a.severity] - order[b.severity];
    });

    for (const scenario of sorted) {
      lines.push(`### ${severityEmoji[scenario.severity]} ${scenario.title}`);
      lines.push('');
      lines.push(`**Severity:** ${scenario.severity.toUpperCase()}`);
      lines.push('');
      lines.push(scenario.description);
      lines.push('');
      
      if (scenario.realWorldExample) {
        lines.push(`> **Real-world precedent:** ${scenario.realWorldExample}`);
        lines.push('');
      }

      lines.push('**Recommended Mitigations:**');
      for (const mitigation of scenario.mitigations) {
        lines.push(`- ${mitigation}`);
      }
      lines.push('');
    }
  }

  // Issues by Category
  if (result.issues.length > 0) {
    lines.push('## Issues by Category');
    lines.push('');

    const issuesByCategory = new Map<string, typeof result.issues>();
    for (const issue of result.issues) {
      const existing = issuesByCategory.get(issue.category) || [];
      issuesByCategory.set(issue.category, [...existing, issue]);
    }

    for (const [category, issues] of issuesByCategory) {
      const categoryMeta = result.categories.find(c => c.category === category);
      lines.push(`### ${categoryMeta?.label || category}`);
      lines.push('');

      for (const issue of issues) {
        lines.push(`#### ${severityEmoji[issue.severity]} ${issue.title}`);
        lines.push('');
        lines.push(`**Severity:** ${issue.severity}`);
        if (issue.location) {
          lines.push(`**Location:** \`${issue.location}\``);
        }
        lines.push('');
        lines.push(issue.description);
        lines.push('');
        lines.push(`**Recommendation:** ${issue.recommendation}`);
        lines.push('');
      }
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*This report was generated by the Ethical Framework Review tool. It is designed to surface potential concerns, not make final judgments. Human review is recommended.*');

  return lines.join('\n');
}

export function exportAsJSON({ result, capabilities, misuseScenarios }: ExportData): string {
  return JSON.stringify({
    projectName: result.projectName,
    timestamp: result.timestamp,
    overallStatus: result.overallStatus,
    summary: {
      totalIssues: result.issues.length,
      detectedCapabilities: capabilities.length,
      misuseScenarios: misuseScenarios.length,
      criticalMisuseCount: misuseScenarios.filter(s => s.severity === 'critical').length,
    },
    capabilities,
    misuseScenarios,
    issues: result.issues,
    categories: result.categories,
  }, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportReport(data: ExportData, format: 'markdown' | 'json') {
  const timestamp = new Date().toISOString().split('T')[0];
  const safeName = data.result.projectName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  
  if (format === 'markdown') {
    const content = exportAsMarkdown(data);
    downloadFile(content, `ethics-review-${safeName}-${timestamp}.md`, 'text/markdown');
  } else {
    const content = exportAsJSON(data);
    downloadFile(content, `ethics-review-${safeName}-${timestamp}.json`, 'application/json');
  }
}
