import { useState, useEffect, useMemo } from 'react';
import { CategorySummary, EthicsIssue, HarmCategory } from '@/types/ethics';
import { SeverityBadge } from './SeverityBadge';
import { CategoryIcon } from './CategoryIcon';
import { cn } from '@/lib/utils';
import { Copy, Check, Rocket, CircleDashed, CircleCheck, CircleDot } from 'lucide-react';
import { toast } from 'sonner';
import { usePlainLanguage } from '@/contexts/PlainLanguageContext';
import { PLAIN_CATEGORY_LABELS } from '@/data/plainLanguageMap';

type CheckState = 'unchecked' | 'acknowledged' | 'resolved';

const CHECK_CYCLE: CheckState[] = ['unchecked', 'acknowledged', 'resolved'];

const checkConfig: Record<CheckState, { icon: typeof CircleDashed; label: string; className: string }> = {
  unchecked: {
    icon: CircleDashed,
    label: 'Not reviewed',
    className: 'text-muted-foreground hover:text-foreground',
  },
  acknowledged: {
    icon: CircleDot,
    label: 'Acknowledged',
    className: 'text-[hsl(var(--ethics-medium))]',
  },
  resolved: {
    icon: CircleCheck,
    label: 'Resolved',
    className: 'text-[hsl(var(--ethics-safe))]',
  },
};

interface PreLaunchChecklistProps {
  categories: CategorySummary[];
  issues: EthicsIssue[];
  timestamp: string;
}

export function PreLaunchChecklist({ categories, issues, timestamp }: PreLaunchChecklistProps) {
  const storageKey = `gfc_checklist_${timestamp}`;
  const { isPlainLanguage } = usePlainLanguage();
  const [copiedChecklist, setCopiedChecklist] = useState(false);

  const [states, setStates] = useState<Record<string, CheckState>>(() => {
    try {
      const saved = sessionStorage.getItem(storageKey);
      if (saved) return JSON.parse(saved);
    } catch {}
    return {};
  });

  useEffect(() => {
    sessionStorage.setItem(storageKey, JSON.stringify(states));
  }, [states, storageKey]);

  const topIssuePerCategory = useMemo(() => {
    const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, safe: 4 };
    const map: Record<string, EthicsIssue> = {};
    for (const cat of categories) {
      const catIssues = issues
        .filter(i => i.category === cat.category)
        .sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);
      if (catIssues.length > 0) map[cat.category] = catIssues[0];
    }
    return map;
  }, [categories, issues]);

  const getState = (cat: string): CheckState => states[cat] || 'unchecked';

  const cycleState = (cat: string) => {
    const current = getState(cat);
    const nextIdx = (CHECK_CYCLE.indexOf(current) + 1) % CHECK_CYCLE.length;
    setStates(prev => ({ ...prev, [cat]: CHECK_CYCLE[nextIdx] }));
  };

  const reviewedCount = categories.filter(
    c => getState(c.category) === 'acknowledged' || getState(c.category) === 'resolved'
  ).length;
  const totalCount = categories.length;
  const allReviewed = reviewedCount === totalCount;
  const progressPercent = totalCount > 0 ? (reviewedCount / totalCount) * 100 : 0;

  const generateMarkdown = () => {
    const lines = [
      '## Pre-Launch Ethics Checklist',
      '',
      ...categories.map(cat => {
        const state = getState(cat.category);
        const check = state === 'resolved' ? 'x' : state === 'acknowledged' ? '~' : ' ';
        const topIssue = topIssuePerCategory[cat.category];
        const label = isPlainLanguage
          ? PLAIN_CATEGORY_LABELS[cat.category as HarmCategory] || cat.label
          : cat.label;
        const issueLine = topIssue ? ` — ${topIssue.title} (${topIssue.severity})` : ' — No issues';
        return `- [${check}] **${label}**${issueLine}`;
      }),
      '',
      `> ${reviewedCount}/${totalCount} categories reviewed.`,
      '> Generated by Ground Floor Check.',
    ];
    return lines.join('\n');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateMarkdown());
    setCopiedChecklist(true);
    toast.success('Checklist copied to clipboard');
    setTimeout(() => setCopiedChecklist(false), 2000);
  };

  return (
    <div className="space-y-5">
      {/* Progress */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <span className="font-mono text-xs text-muted-foreground">
            {reviewedCount} of {totalCount} categories reviewed
          </span>
          <button
            onClick={handleCopy}
            className={cn(
              'inline-flex items-center gap-1.5 px-3 py-1.5 rounded border text-xs font-mono transition-colors',
              copiedChecklist
                ? 'border-[hsl(var(--ethics-safe)/0.4)] text-[hsl(var(--ethics-safe))] bg-[hsl(var(--ethics-safe)/0.08)]'
                : 'border-border text-muted-foreground hover:text-foreground hover:border-primary/30'
            )}
          >
            {copiedChecklist ? <Check size={12} /> : <Copy size={12} />}
            {copiedChecklist ? 'Copied' : 'Copy checklist'}
          </button>
        </div>
        <div className="h-2 bg-secondary rounded-full overflow-hidden">
          <div
            className={cn(
              'h-full rounded-full transition-all duration-500',
              allReviewed ? 'bg-[hsl(var(--ethics-safe))]' : 'bg-primary'
            )}
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Ready banner */}
      {allReviewed && (
        <div className="p-4 rounded-lg border border-[hsl(var(--ethics-safe)/0.3)] bg-[hsl(var(--ethics-safe)/0.06)] flex items-start gap-3 animate-slide-in">
          <Rocket size={18} className="text-[hsl(var(--ethics-safe))] shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-foreground">Ready to launch</p>
            <p className="text-xs text-muted-foreground mt-1">
              You've reviewed all harm categories. This doesn't mean the app is safe — it means you've made an informed decision about each risk.
            </p>
          </div>
        </div>
      )}

      {/* Category rows */}
      <div className="space-y-2">
        {categories.map(cat => {
          const state = getState(cat.category);
          const config = checkConfig[state];
          const Icon = config.icon;
          const topIssue = topIssuePerCategory[cat.category];
          const displayLabel = isPlainLanguage
            ? PLAIN_CATEGORY_LABELS[cat.category as HarmCategory] || cat.label
            : cat.label;

          return (
            <div
              key={cat.category}
              className={cn(
                'flex items-center gap-3 p-3 rounded-lg border transition-all',
                state === 'resolved'
                  ? 'border-[hsl(var(--ethics-safe)/0.2)] bg-[hsl(var(--ethics-safe)/0.03)]'
                  : state === 'acknowledged'
                  ? 'border-[hsl(var(--ethics-medium)/0.2)] bg-[hsl(var(--ethics-medium)/0.03)]'
                  : 'border-border bg-card hover:border-border/80'
              )}
            >
              {/* Cycle checkbox */}
              <button
                onClick={() => cycleState(cat.category)}
                className={cn('shrink-0 transition-colors', config.className)}
                title={config.label}
              >
                <Icon size={22} />
              </button>

              {/* Category icon */}
              <div className="p-1.5 rounded bg-secondary/60 shrink-0">
                <CategoryIcon icon={cat.icon} size={16} />
              </div>

              {/* Content */}
              <div className="flex-1 min-w-0">
                <p className="font-mono text-sm font-medium text-foreground truncate">
                  {displayLabel}
                </p>
                {topIssue ? (
                  <p className="text-xs text-muted-foreground truncate mt-0.5">
                    {topIssue.title}
                  </p>
                ) : (
                  <p className="text-xs text-muted-foreground/50 mt-0.5 italic">No issues found</p>
                )}
              </div>

              {/* Severity badge */}
              {topIssue && (
                <SeverityBadge severity={topIssue.severity} size="sm" />
              )}

              {/* State label */}
              <span className={cn('font-mono text-[10px] shrink-0 w-20 text-right', config.className)}>
                {config.label}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}
